docs: condense "Writing policies" section
kubewarden/.github pull request #20
Opened 2024-11-12 19:56 UTC by agilgur5

## Description

Closes #19 by heavily condensing the section in general instead of fixing outdated links

- link out to the [docs page on "Writing Policies"](https://docs.kubewarden.io/tutorials/writing-policies) instead

- misc `markdownlint` newline autofixes

## Test

See the rendered markdown [rich diff](https://github.com/kubewarden/.github/pull/19/files?short_path=0e83982#diff-0e83982cf6f4dabedcbf7b12029a56c6f4a728064ba99543fff8f227c0654b45)

## Additional Information

### Tradeoff

n/a

### Potential improvement

n/a

2024-11-13 09:00 UTC, kkaempf requested changes
Thanks for your PR !

However, while I agree that the table should be condensed, the language keywords (Rust, Go, ...) better stay for visibility.

2024-11-14 10:09 UTC, flavio commented
I've applied the changes requested by @kkaempf 

@agilgur5: thanks a lot for your contribution! :heart:

2024-11-14 10:09 UTC, merged

2024-11-14 23:00 UTC, agilgur5 reviewed
> I've applied the changes requested by @kkaempf

Thanks @flavio, I like the [content changes](https://github.com/kubewarden/.github/pull/20/commits/23924ba115c9d71d688ad425cf7035f297b4bcfe) you made!
(although the spacing doesn't quite pass `markdownlint` 😅 )

2024-11-14 23:00 UTC, agilgur5 commented on profile/README.md
> + - [Policy templates](https://github.com/kubewarden/community/#policies-templates): boilerplate code to help you get started 🚀
```suggestion

- [Step-by-step tutorials](https://docs.kubewarden.io/tutorials/writing-policies) inside of our documentation 📖
- [Policy SDKs](https://github.com/kubewarden/community/#policies-sdks): overview of the Policy SDKs available, and their maturity level 📚
- [Policy templates](https://github.com/kubewarden/community/#policies-templates): boilerplate code to help you get started 🚀 
```

- adjust spacing to pass `markdownlint` (new line before the list and no space before the hyphen)
- "SDK" -> "SDKs"